config/routes.rb
Rails.application.routes.draw do

  root   'static_pages#home'
  get    '/signup', to: 'users#new'
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get    '/edit-basic-info/:id', to: 'users#edit_basic_info', as: :basic_info
  patch  'update-basic-info', to: 'users#update_basic_info'
  get    'users/:id/attendances/:date/edit', to: 'attendances#edit', as: :edit_attendances
  patch  'users/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances
  
  resources :users do
    resources :attendances, only: :create
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :department, length: {in: 3..50}, allow_blank: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy, :edit_basic_info, :update_basic_info]
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  # 新規登録ページ
  def new
    @user = User.new
  end
  
  # 勤怠表示ページ
  def show
    @user = User.find(params[:id])
    
    # if params[:first_day].nil?
    #   @first_day = Date.today.beginning_of_month
    # else
    #   @first_day = Date.parse(params[:first_day])
    # end
    @first_day = first_day(params[:first_day])  #first_dayはAttendancesHelper
    @last_day = @first_day.end_of_month
    
    (@first_day..@last_day).each do |day|
      unless @user.attendances.any? {|attendance| attendance.worked_on == day}
        record = @user.attendances.build(worked_on: day)
        record.save
      end
    end
    @dates = @user.attendances.where('worked_on >= ? and worked_on <= ?', @first_day, @last_day).order('worked_on')
    @work_sum = @dates.where.not(started_at: nil).count
  end
  
  # 新規登録→ログイン状態へ
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ユーザーの新規作成に成功しました。"
      redirect_to @user
    else
      render "new"
    end
  end
  
  def edit
    # correct_userが先に実行されるため、@user定義なし
  end
  
  def update
    # correct_userが先に実行されるため、@user定義なし
    if @user.update_attributes(user_params)
      flash[:success] = "更新しました。"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "削除しました。"
    redirect_to users_url
  end
  
  # 基本情報編集ページ
  def edit_basic_info
    @user = User.find(params[:id])
  end
  
  # 基本情報更新
  def update_basic_info
    @user = User.find(params[:id])
    if @user.update_attributes(basic_info_params)
      flash[:success] = "基本情報を更新しました。"
      redirect_to @user
    else
      render 'edit_basic_info'
    end
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :department, :password, :password_confirmation)
    end
    
    def basic_info_params
      params.require(:user).permit(:basic_time, :work_time)
    end
    
    # beforeアクション
    
    # ログイン済みユーザーか確認
    def logged_in_user
      #if not logged_in? 以下と同義
      unless logged_in?
        store_location
        flash[:warning] = "ログインしてください。"
        redirect_to login_url
      end
    end
    
    # 正しいユーザーか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to (root_url) unless current_user?(@user)  #current_user?()はSessionsHelperで定義
    end
    
    # 管理者かどうか確認
    def admin_user
      redirect_to (root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  # 基本時間などの値を、指定の書式にフォーマットして返す
  def format_basic_time(datetime)
    format("%.2f", ((datetime.hour * 60) + datetime.min) /60.0)
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>
  
  <%= f.label :department %>
  <%= f.text_field :department, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "基本情報編集", basic_info_path(user) %>
    | <%= link_to '削除', user, method: :delete, data: {confirm: '削除してよろしいですか。'} %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "アカウント編集") %>
<% provide(:button_text, "更新する") %>
<h1>アカウント情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, "基本情報編集") %>
<h1>基本情報の編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: update_basic_info_path(params: {id: @user.id})) do |f| %>
      <%= render '/shared/error_messages', object: @user %>
      
      <%= f.label :basic_time %>
      <%= f.time_field :basic_time, class: 'form-control' %>
      
      <%= f.label :work_time %>
      <%= f.time_field :work_time, class: 'form-control' %>
      
      <%= f.submit "更新する", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "一覧") %>
<h1>ユーザー一覧</h1>
<%= will_paginate %>

<ul class="users">
  <%# @users.each do |user| %>
    <%= render @users %>
  <%# end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'ユーザー作成') %>
<% provide(:button_text, '作成する') %>
<h1>アカウント作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "勤怠表示") %>
<div>
  <table class="table-bordered table-condensed">
    <tr>
      <td>
        <%= link_to "←", user_path(params: {id: @user.id, first_day: @first_day.prev_month}), class: "btn btn-xs btn-primary" %>
        &emsp;<%= @first_day.to_s(:year_month) %> 時間管理表&emsp;
        <%= link_to "→", user_path(params: {id: @user.id, first_day: @first_day.next_month}), class: "btn btn-xs btn-primary" %>
      </td>
      <td>指定勤務時間：<%= format_basic_time(@user.work_time) %></td>
      <td>基本時間：<%= format_basic_time(@user.basic_time) %></td>
      <td>初日 <%= @first_day.to_s(:date) %></td>
    </tr>
    
    <tr>
      <td>所属：<%=@user.department.present? ? @user.department : "未設定" %></td>
      <td>氏名：<%= @user.name %></td>
      <td>出勤日数：<%= @work_sum %>日</td>
      <td>末日 <%= @last_day.to_s(:date) %></td>
    </tr>
  </table>

  <%= link_to "勤怠を編集", edit_attendances_path(id: @user, date: @first_day), class: "btn btn-primary" %>
  <!-- テーブル -->
  <table class="table-bordered table-striped table-condensed">
    <thead>
      <tr><!--rowspan:縦結合、colspan：横結合-->
        <th rowspan="2">日付</th>
        <th rowspan="2">曜日</th>
        <th colspan="3">出社</th>
        <th colspan="3">退社</th>
        <th rowspan="2">在社時間</th>
        <th rowspan="2">備考</th>
      </tr>
      
      <tr>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th></th>
      </tr>
    </thead>
    
    <!-- データ部分 -->
    <tbody>
      <% @dates.each do |day| %>
        <tr>
          <td><%= day.worked_on.to_s(:date) %></td>
          <td><%= %w{日 月 火 水 木 金 土 日}[day.worked_on.wday] %></td>
          <td><%= day.started_at.to_s(:hour) if day.started_at.present? %></td>
          <td><%= day.started_at.to_s(:min) if day.started_at.present? %></td>
          <td>
            <% if day.worked_on == Date.today && day.started_at.nil? %>
              <%= button_to "出社", user_attendances_path(@user), class: "btn btn-xs btn-primary" %>
            <% end %>
          </td>
          <td><%= day.finished_at.to_s(:hour) if day.finished_at.present? %></td>
          <td><%= day.finished_at.to_s(:min) if day.finished_at.present? %></td>
          <td>
            <% if day.worked_on == Date.today && day.started_at.present? && day.finished_at.nil? %>
              <%= button_to "退勤", user_attendances_path(@user), class: "btn btn-xs btn-primary" %>
            <% end %>
          </td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= working_times(day.started_at, day.finished_at) %>  <!-- working_timesはAttendancesHelper -->
              <% seconds = (day.finished_at - day.started_at).to_i %>
              <% @total_seconds = @total_seconds.to_i + seconds %>
            <% end %>
          </td>
          <td><%= day.note %></td>
        </tr>
      <% end %>
    </tbody>
    
    <!-- フッター部分 -->
    <tfoot>
      <tr>
        <td colspan="2">総合勤務時間 <%= format_basic_time(@user.basic_time).to_f * @work_sum %></td> <!-- format_basic_timeはUsersHelper -->
        <td colspan="6"></td>
        <td>在社時間合計 <%= working_times_sum(@total_seconds) unless @total_seconds.nil? %></td>
        <td></td>
      </tr>
    </tfoot>
  </table>
</div>